export const GET_MYBOOKINGS = 'GET_MYBOOKINGS';
export const SET_MYBOOKINGS = 'SET_MYBOOKINGS';
export const GET_MYBOOKING_CLICKED = 'GET_MYBOOKINGS_CLICKED';
export const SET_MYBOOKING_CLICKED = 'SET_MYBOOKINGS_CLICKED';
export const SET_TOTAL_BOOKINGS = 'SET_TOTAL_BOOKINGS';
export const OPEN_MODAL_FILTER = 'OPEN_MODAL_FILTER';
export const CLOSE_MODAL_FILTER = 'CLOSE_MODAL_FILTER';
