export const SET_BOOKING_REVIEW = 'SET_BOOKING_REVIEW';
export const SET_BOOKING_REVIEW_RESPONSE = 'SET_BOOKING_REVIEW_RESPONSE';
export const SET_REPORT_REVIEW = 'SET_REPORT_REVIEW';
export const SET_REPORT_REVIEW_RESPONSE = 'SET_REPORT_REVIEW_RESPONSE';
