export const OPEN_MODAL_SU = 'OPEN_MODAL_SU';
export const CLOSE_MODAL_SU = 'CLOSE_MODAL_SU';
export const GET_ALL_ASSIGNED_STAFF = 'GET_ALL_ASSIGNED_STAFF';
export const SET_ALL_ASSIGNED_STAFF = 'SET_ALL_ASSIGNED_STAFF';
export const REVOKE_ROLE = 'REVOKE_ROLE';
export const GET_ALL_UNSIGNED_STAFF = 'GET_UNSIGNED_STAFF';
export const SET_ALL_UNSIGNED_STAFF = 'SET_ALL_UNSIGNED_STAFF';
export const SET_STAFF_TO_ROLE = 'SET_STAFF_TO_ROLE';