version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sarpras
    restart: always
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - /app/node_modules
      