export const OPEN_MODAL_FILTER = 'OPEN_MODAL_FILTER';
export const CLOSE_MODAL_FILTER = 'CLOSE_MODAL_FILTER';
export const GET_FACILITIES = 'GET_FACILITIES';
export const SET_FACILITIES = 'SET_FACILITIES';
