export const OPEN_MODAL_FILTER = 'OPEN_MODAL_FILTER';
export const CLOSE_MODAL_FILTER = 'CLOSE_MODAL_FILTER';
export const POST_REPORT = 'POST_REPORT';
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS';
