export const GET_BOOKING_LIST = 'GET_BOOKING_LIST';
export const SET_BOOKING_LIST = 'SET_BOOKING_LIST';
export const OPEN_MODAL_FILTER = 'OPEN_MODAL_FILTER';
export const CLOSE_MODAL_FILTER = 'CLOSE_MODAL_FILTER';
export const GET_BOOKING = 'GET_BOOKING';
export const SET_BOOKING = 'SET_BOOKING';
